### ISSUE TITLE
Unable to change/write temperature manual

### ISSUE THREAD

**Issue by Nakle** [robertklep/bosch-xmpp#11]
Hi,
I am having problem setting the temperature `manualRoomSetpoint`
Getting `Unhandled rejection SyntaxError: Unexpected token v in JSON at position 1` with this : 

- `bosch-xmpp` ivt put /heatingCircuits/hc1/manualRoomSetpoint '{"value":20.5}'

I am having no problem reading (GET).
Also, I have created the environmental variables with correct info.

**Comment by robertklep** [comment]
It's possible the endpoint you're using doesn't exist for IVT devices. The only ones I know that are related to heating circuits are:
```
/heatingCircuits/hc1/activeSwitchProgram
/heatingCircuits/hc1/heatingCurveSettings
/heatingCircuits/hc1/holidayMode
/heatingCircuits/hc1/operationMode
/heatingCircuits/hc1/roomTemperature
/heatingCircuits/hc1/status
/heatingCircuits/hc1/switchPrograms
/heatingCircuits/hc1/temperatureLevels
/heatingCircuits/hc1/temperatureRoomSetpoint
```
(these come from a decompiled Bosch app)
