### ISSUE TITLE
Not all history values are listed when reading out energy on CT200

### ISSUE THREAD

**Issue by albert607** [robertklep/bosch-xmpp#17]
When reading out the CT200 history settings using the following command, I only see the first 20 entries
> bosch-xmpp easycontrol get /energy/history 

When running following command I see that actually 43 entries are available:
> bosch-xmpp easycontrol get /energy/historyEntries 

Is there a command/possibility to read out the next 20 entries or even read only 1 entry (by giving the value number)?

(I am fairly new to xmpp so perhaps there is a detailed help page somewhere, but I could not find it.)

**Comment by robertklep** [comment]
The history data is paginated. I can't test myself if this works, but try retrieving `/energy/history?entry=0` (and `/energy/shower/history?entry=1`, etc). You probably need to quote the endpoint on the command line:
```
bosch-xmpp easycontrol get '/energy/history?entry=0'
```

**Comment by albert607** [comment]
Thank you for the fast response. Your answer did the trick!
Actually when providing an entry number it lists that one and all successive entries till the end too.
