### ISSUE TITLE
Support IVT IP module

### ISSUE THREAD

**Issue by deric** [robertklep/bosch-xmpp#18]
Any chance to support IVT's IP module that comes with IVT AIR X / Airmodule?

`nmap` indentifies the device as `Bosch Logamatic Gateway web KM200`.
```
$ nmap -A -T4 10.0.0.136
Starting Nmap 7.80 ( https://nmap.org ) at 2021-06-23 12:36 CEST
Nmap scan report for 10.0.0.136
Host is up (0.018s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE VERSION
80/tcp open  http    Bosch Logamatic Gateway web KM200 httpd
|_http-title: Site doesn't have a title (text/html).
Service Info: Device: specialized
```
It returns empty responses for `GET /`
```
$ curl -I 10.0.0.136
HTTP/1.0 200 The request has succeeded
Content-Type: text/html
Expires: Sun, 03 Jan 2100 12:00:00 GMT
```
for any other tested request, e.g. `/system/info` it returns
```
<HTML><HEAD><TITLE>Gateway webserver</TITLE></HEAD><DIV ALIGN=CENTER><FONT SIZE=+4><BR><BR><BR>Sorry, the requested file does not exist on this server.</FONT></DIV></HTML>
```

**Comment by robertklep** [comment]
If the device doesn't use XMPP, it's not supported. I never really looked at HTTP support.

**Comment by deric** [comment]
The only open port I found is `80`. The manual says that the local network must support DHCP and ports `5222` and `5233` can't be blocked for outgoing communication. The IP address shown on the device is probably located in Norway (unlike the device itself), registered to `Telenor Norge AS` (which might be XMPP gateway, or just reverse proxy).

Given proper header, the device seem to respond with encrypted response:
```
$ curl -H "User-Agent: TeleHeater/1.0.0" 10.0.0.136/system/brand

u/UYsGcba/PNsiELCEOxtnhtdg8KWLaRkE7AdBaHe3/T+UCyAt74P5cSzy91rgL8GnUMlMm022iV3iQWqKvf3r0WOGlQRAoxCr2ydZCvoNxfQStT1vLBxYuRMkof65zRZA36yE//TVDjtEJOz/mREWnv4g/9qp5nleySLdSJwSse/rb1Yz7Y3U3UfjoLwp+/Mcq9X0hdhtxwuHsHHifPYX2nHBAoSW+EhMO5jpMpMqTs49L1FImIVYldwkPFxffueP8gaeFZ5FNylEw/M/iPxGX4Q43O3Y9hspF/evTcVPfs6vLfISI50MEOFOqp+a75KpX9lQLS2LKvJgygWlxT6I7/X3Ef7oYnjUoQ0kvqmKk=
```

**Comment by robertklep** [comment]
In case of XMPP, the device will make a connection to the Bosch cloud servers, which doesn't require an open port on the device itself. Have you tried using `bosch-xmpp` to see if it works?

**Comment by deric** [comment]
Yes, but I'm always getting `Unhandled rejection XMPP authentication failure`. Is there some request that doesn't require authentication?

**Comment by robertklep** [comment]
No, all requests require authentication. For XMPP, the serial number and access key are used.

**Comment by deric** [comment]
I've tried the same credentials that I've used for IVT Anywhere registration, but without success.

**Comment by robertklep** [comment]
I don't have access to such a device so can't help out apart from providing some general guidelines. Since the device identifies as "KM200", I expect it to work because (AFAIK) that device is supported. Which client(s) have you tried?

**Comment by deric** [comment]
I've tried `ivt`,`nefit` and `easycontrol`. All with the same result. 
```
$ bosch-xmpp --serial=2600-139-000267-xxxxxxxxxx --access-key=138xxxxxx --password=xxxx-xxxx-xxxx-xxxx ivt get /system/info
$ bosch-xmpp -v
1.2.0
```

**Comment by robertklep** [comment]
Swap around the serial number and the access key.

**Comment by deric** [comment]
Still the same, I've tried it with dashes, without. All the same.

**Comment by robertklep** [comment]
I only have (had) a Nefit Easy and an EasyControl CT200. For both those devices, the access key is a 16-character string consisting of upper- and lowercase letters (a-z, A-Z), and the serial number is a 9-digit number. The password is chosen when you first initialize the device with its mobile app (but the password is not used for XMPP authentication, only for encryption/decryption).

**Comment by deric** [comment]
Finally it works.
```
$ bosch-xmpp --serial=1xxxxxxxx --access-key=xXxx-Xxxx-xxXx-xxx --password=userPassword ivt get /system/systemType
{"id":"/system/systemType","type":"stringValue","writeable":0,"recordable":0,"value":"NSC_ICOM_GATEWAY","allowedValues":["NSC_ICOM_GATEWAY"]}
```

- `serial` is username from IP-Modul
- `access-key` is generated password from IP-Modul
- `password` is user-configured password

**Comment by fsvenson** [comment]
Hi, 

I'm also trying to connect to an IVT heat pump that came with the house I bought this summer. It appears I have the exact same IP module as @deric describes, I get the same kind of encrypted responses when making requests via cURL.

My issue appears to be actually setting a user password. When trying to add the heat pump via IVT Anywhere I get a "Could not connect to gateway" message when trying to set the password. I have also tried using the physical reset button on the IP module as well as resetting the password on the control panel of the heat pump. None of this appears to help.

What's curious is also that when looking through the settings on the heat pump control panel, it doesn't seem like the IP module is active somehow. All of the fields relating to it are empty and SW version says 0.0. And in the service menu it says that the IP Module is "Invalid". Any guesses as to what is at play here? Does anyone know if there is a default user password I could use to decrypt the API responses?

Thanks for any help!

**Comment by deric** [comment]
@fsvenson There are two versions the app on Google Play. I was using  [IVT Anywhere](https://play.google.com/store/apps/details?id=com.bosch.tt.IVT&hl=en&gl=US) for setting the password, it allows local connections. The second version [IVT Anywhere II](https://play.google.com/store/apps/details?id=com.ivt.tt.dashtt&hl=cs&gl=US) is more like a cloud version. You need to have an active DHCP server on local network, in order to obtain some IP address (it might be good idea to assign it a permanent lease).

**Comment by fsvenson** [comment]
@deric thanks for your quick response. Yes, I used the earlier app version, but seemingly to no avail. I ran a packet sniffer yesterday when trying to add it via the app and this screenshot shows the last messages captured.
![Screenshot_20220925-160948_Packet Capture.jpg](https://user-images.githubusercontent.com/15660751/192148061-20836c24-a593-4b13-af0a-c42b48575a01.jpg)

It looks curiously similar to the response I got when curling the same endpoint. So I would assume that the issue is the same in the app, i.e. the responses are not decrypted. So I'm thinking a previous owner might have set a password but I appear to have no way to reset it? Maybe IVT/Bosch support could do that? Unless there is some root user or default password I could use to reset it.

**Comment by deric** [comment]
@fsvenson When you look at the [decrypting part of the code](https://github.com/robertklep/bosch-xmpp/blob/master/lib/ivt-client.js#L15) it consists of two parts

```
 decryption_key = md5("{accessKey}{MAGIC}") md5("{MAGIC}{password}")
```
where `MAGIC` is a well-known string specific for each brand (e.g. IVT) and `accessKey` is printed on the IP Module (called "Passwort") see e.g. [home assistant component](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki).

Although you know 3/4 of required inputs and `md5` is considered as a weak hashing algorithm, burte-forcing the password might take quite a while. The number of requests on the local network is probably not limited (the XMPP servers might have some limits per IP), but the initial password is stored in your IP module's memory (and you can't easily access it).

Your easiest option might be to get the password from the original owner, reset the IP Module into factory settings or contact Bosch service.

According to [Buderus KM200 manual](https://www.manualslib.de/manual/200315/Buderus-Logamatic-Web-Km200.html?page=16) the reset button should be on the board and you should hold it for 6 seconds:

![Screenshot_20220926_195530](https://user-images.githubusercontent.com/138573/192347080-8b357f01-9e18-4622-9b01-392a747ef6c5.png)

It case of IVT the module seems to be sealed and probably not expected to be opened by the customer. You might loose warranty (if you have any).

Yes, you can see the plain text requests, that's correct:
```
GET /gateway/versionFirmware
```
but the decrypted answer would look like this:
```
[{"id":"/gateway/versionFirmware","type":"stringValue","writeable":0,"recordable":0,"value":"04.08.02"},{"id":"/heatSources/returnTemperature","type":"floatValue","writeable":0,"recordable":0,"value":52.8,"unitOfMeasure":"C","state":[{"open":-3276.8},{"short":3276.7}]}]
```

**Comment by mfalkvidd** [comment]
@fsvenson did you ever get this working? I am in a similar situation, all of the fields relating to the module are empty and SW version says 0.0.
