### ISSUE TITLE
EasyControl CT200 XMPP Connection

### ISSUE THREAD

**Issue by Kinyuu** [robertklep/bosch-xmpp#20]
Hello, @robertklep 
The current XMPP server you are connecting to, Charlie, is going to be migrated to a different one for the CT200. So this should stop working in the next couple of days.
Nevertheless, you can update it to the new one and give it a try once it stops working.
Instead of charlie.ticx.boschtt.net, it should be xmpp.rrcng.ticx.boschtt.net

Best wishes,

**Comment by robertklep** [comment]
@Kinyuu thanks for the notification :D I'll try and see if I can dig out my CT200 within the next few days to test it out.

**Comment by Kinyuu** [comment]
Charlie should stop working entirely past version 3.6.2 on the gateway itself, FYI!

**Comment by robertklep** [comment]
Just released `bosch-xmpp@1.3.0` with an updated XMPP host for the EasyControl client.
