### ISSUE TITLE
Logomax (buderus) tc100 v2

### ISSUE THREAD

**Issue by fate8383** [robertklep/bosch-xmpp#21]
Hi there, thanks for looking into this. I have spent many hours to look for something for my homebridge to control or at least view tc100 v2. This is something i have not tried yet but I have some questions. how do i go about doing this as homebridge plugin? I read the WIKI but not sure if I just install on command line it will appear in homebridge or homebridge UI? I am not very good at APIs and all but this tc100 v2 is using app called "my mode" as oppose to v1 "easy mode or easy control" and it is fully bosch id authenticated and wifi only working control. It is technically the same but I am not sure how can I use this as homebridge plugin? Could you please help me a little bit?
Thanks a lot!

**Comment by robertklep** [comment]
You would need a specific Homebridge plugin, which (AFAIK) doesn't exist.

**Comment by fate8383** [comment]
There is one now. https://github.com/lynxcs/homebridge-ct200 and i can confirm it is working with tc100 v2. thanks a lot!
