### ISSUE TITLE
CT200 returning some string values as base64 string

### ISSUE THREAD

**Issue by Bulforce** [robertklep/bosch-xmpp#23]
When getting list of weekly schedules

```bash
bosch-xmpp easycontrol get /programs/list
>>>
{"id":"/programs/list","type":"programArray","writeable":0,"recordable":0,"value":[
  ---
  {"id":3,"name":"MjVDIE9O"}
]}
```

The name value I see in the terminal is base64 encoded string, the actual value in the above case is '25C ON'.
Do you think this has something to do with this client implementation, or perhaps the rrc rest api is returning it like this?

Same happens when I get the list of rooms through /zones/list

**Comment by robertklep** [comment]
That's what the API returns (no idea why, it seems a bit superfluous), the client returns the raw response JSON.

**Comment by Bulforce** [comment]
Oh sorry for the buzz, I just saw that the spec says the name is base64 encoded, so its by design.
Closing this. Sorry again for the spam.
