### ISSUE TITLE
CT200 put request makes no changes

### ISSUE THREAD

**Issue by thepasto** [robertklep/bosch-xmpp#24]
Hello, i tried to make a room temperature change via a put request using this client.

```
(async () => {
    await client.connect();
    try {
        console.log('%j', await client.put('/zones/zn1/clockOverride/temperatureHeating','{"value":25}'));
    } catch(e) {
        console.error(e.stack || e);
    }
    client.end();
})();
```

the response was successfully, {"status":"ok"}.
But i can't see no changes on the thermostat display. Manual mode is already setted on.

The same result i got if i run it via command line.
What am i missing?

Any clue? Thanks for the help

**Comment by robertklep** [comment]
Try putting a proper object instead of a JSON string:
```
await client.put('/zones/zn1/clockOverride/temperatureHeating', { value : 25 })
```

Also, make sure that the endpoint is actually writable. You should be able to see that when you retrieve it.

**Comment by thepasto** [comment]
Thanks, json string seems to work better, anyway it was the wrong path... My mistake, manual mode temp is here /gateways/{deviceId}/resource/zones/{zoneId}/manualTemperatureHeating

Thank you for your work
