### ISSUE TITLE
Connecting to Bosch heatpump (Compress 7400)

### ISSUE THREAD

**Issue by axel-loewe** [robertklep/bosch-xmpp#30]
Hi,

Did anyone manage to connect to a Bosch heatpump with an HPC 400 control panel? I'm puzzled which information from the sticker on the machine to put in which variable and whether to include the dashes or not. 

Thanks,
Axel

**Comment by robertklep** [comment]
Which information do you have? I think the access key is the one that has dashes, but the client (`ivt`) should take care of that. If not, just try with and without.

**Comment by axel-loewe** [comment]
Figured it out. `serial` is what's printed as _Loginname_, `access-key` is what's printed as _Passwort_ and `password` is what was set manually during setup.

However, the responses seem to be encoded/encrypted in some way.
```bosch-easyremote received stanza of type "message" +136ms
  bosch-easyremote:raw <message from="gateway_040421408@wa2-mz36-qrmzh6.bosch.de/iCom-RestApi" to="contact_040421408@wa2-mz36-qrmzh6.bosch.de/34xhd7wygn" xmlns:stream="http://etherx.jabber.org/streams">
  bosch-easyremote:raw <body>HTTP/1.0 200 The request has succeeded
  bosch-easyremote:raw Content-Type: application/json
  bosch-easyremote:raw 
  bosch-easyremote:raw 
  bosch-easyremote:raw eOiZ/+I7BnP+QpX4zz5jwUfBhqdd4/8BuLU5vOoodafd7t0APIRJdq6acJ9J20LidWJdP4omrvu/x9QhXHUDI5ie2KAQqurGnv6bLF8LExKkElrrwIzT7NWFMqm4Q3oTTD8I+++aWlnz7O0WhT0u2g==</body>
  bosch-easyremote:raw </message> +136ms
  bosch-easyremote cleaning up for /gateway/versionFirmware +3ms
SyntaxError: Unexpected token ; in JSON at position 0
```

**Comment by robertklep** [comment]
Yes, data is always encrypted. However, the client implementation should decrypt it.

Instead of just using your password, can you try and use a Base64-encoded version of it? Your issue could be related to #14 (which was fixed a few days ago, but not yet published). Or install the current Github version of the package:
```
npm install -g robertklep/bosch-xmpp
```

**Comment by axel-loewe** [comment]
I used the wrong password 🙈 

Works perfectly with the correct password (not when providing the base64-encoded one, though).

Thanks a lot for your support and the great work!
