### ISSUE TITLE
Authentication Failure to A/C i3000

### ISSUE THREAD

**Issue by neugartf** [robertklep/bosch-xmpp#35]
Hey!

I'm trying to connect to an indoor unit of [Bosch's i3000](https://www.bosch-thermotechnology.com/de/de/ocs/wohngebaeude/climate-3000i-19079695-p/) model. This unit can by controlled with their "HomeCom Easy" app. 
I see that this is not necessarily supported with this client, but I used it as a starting point to connect to it.

Some collected information:
- The unit seems to talk to `xmpp.rac.ticx.boschtt.net`, which also is using `SCRAM-SHA-1`.
- Checking the HomeCom Easy apk it seems that the mobile app itself talks to the backend via http. At least I couldn´t find an xmpp client references on the first check. 
- Trying to login with different CLIENTs (IVT ..) fails with `XMPP authentication failure`.

I saw that there is an `ACCESS_KEY` defined for every client. Assuming this might be why it fails: can someone give me a hint on how to obtain that key? :) 

Thanks!
Fabian

**Comment by robertklep** [comment]
At least for the supported devices, the access key is fixed and typically supplied with the device. There are also two other pieces of information: a serial key (also fixed and supplied) and a password (user-configurable).

How exactly do you configure the device in the mobile app?

**Comment by neugartf** [comment]
Wow, that was fast!

The wifi gateway comes with a `Login Name` and a `Password`, which I already tried.
The setup in the app is quite like with a Chromecast. You connect to the AP of the unit and then link it to your home wifi. You **can´t** assign a specific password in the app afterwards. 

![image](https://user-images.githubusercontent.com/6741676/183288203-3b961763-1e2c-486b-beab-0ca2ab84ecc4.png)

**Comment by robertklep** [comment]
Interesting device 😊

Do you know with certainty that it connects over XMPP, or did you just find that information in the app? I took a look at the app and it's not very clear how exactly it works, but at least with recent(-ish) versions of the Bosch apps a lot of comms handling is done in compiled code (not Java).

**Comment by neugartf** [comment]
Yeah, it is :D

I sniffed the traffic of the indoor unit and XMPP was the only thing that popped up. I didn´t do a thorough investigation of the app traffic though. I will do that later.

```
lib/arm64-v8a/libbarhopper_v3.so
lib/arm64-v8a/libimage_processing_util_jni.so
lib/arm64-v8a/librealm-jni.so
```
I found these compiled libs in the HomeCom app, which don´t look too much to me like they would do much communication. I think there is a general possibility of loading more these on demand on the device. 

I found a ton of Retrofit endpoints in the decompiled java bytecode though, that span over all heating functionality (like setting temperature etc.). They all seem to want to talk to `https://pointt-api.bosch-thermotechnology.com/pointt-api/api/v1/`.

**Comment by robertklep** [comment]
Yeah those libs don't seem very networky. I have no idea what that API is that you mention, it's not used by any of the thermostats.

**Comment by maui1911** [comment]
did you figure this out in anyway @neugartf ?

found something apprently there is a homebridge thing: https://github.com/bulivlad/homebridge-boschclimateseries

**Comment by neugartf** [comment]
Hey @maui1911,
I'm about to release a py package for the API soon-ish. I'll let you know here.

Also thinking about adding this to home assistant, but this will take a bit longer :).

**Comment by githule** [comment]
hello @neugartf :  Did you succeed in connecting your Climate 3000i to a domotic platform or any mqtt or API ? Thanks

**Comment by maui1911** [comment]
There is an alternate usb stick you can use for this https://smlight.tech/product/slwf-01/

There are multiple manufacturers

**Comment by neugartf** [comment]
> hello @neugartf :  Did you succeed in connecting your Climate 3000i to a domotic platform or any mqtt or API ? Thanks

Sorry mate, I moved home and thus don't have access to that unit anymore :/.

**Comment by githule** [comment]
thanks for the reply :)
