### ISSUE TITLE
How to use the BRIDGE when changing a setting

### ISSUE THREAD

**Issue by VanDeStouwe** [robertklep/bosch-xmpp#42]
I like to understand the format for changing a parameter when using the bridge:
Bridge setup:
`C:\Users\Sidney van de Stouwe>bosch-xmpp --serial=x --access-key=x --password=x easycontrol bridge
HTTP server listening on http://127.0.0.1:3000`

GET the setting command:
`C:\Users\Sidney van de Stouwe>curl http://localhost:3000/bridge/zones/zn1/userMode
{"id":"/zones/zn1/userMode","type":"stringValue","writeable":1,"used":"true","recordable":0,"value":"manual"}`

How must I format the command to using the bridge?

**Comment by robertklep** [comment]
```
curl -d '{"value":123}' -H 'content-type: application/json' -XPOST http://localhost:3000/bridge/zones/zn1/userMode
```

**Comment by VanDeStouwe** [comment]
Many thanks for the helping. For windows I found that [double quotes in the JSON data](https://mkyong.com/spring/curl-post-request-examples/) needs escaping:  like in my example:
`C:\Users\Sidney van de Stouwe>curl -H "Content-Type: application/json" -X POST -d {\"value\":\"manual\"} http://localhost:3000/bridge/zones/zn1/userMode

{"status":"ok"}`
