### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Sonusss** [robertklep/bosch-xmpp#6]
Hello,

I tried to install with npm as described but got a lot of errors with 'deprecated' items.
[npm-install.log](https://github.com/robertklep/bosch-xmpp/files/4374601/npm-install.log)
[npm-install.log](https://github.com/robertklep/bosch-xmpp/files/4374609/npm-install.log)

I then tried to install files manually but then always get an error from node when calling the app.

> Error: Cannot find module 'docopt'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/bosch-xmpp-1.0.2/lib/cli/index.js:3:17)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)

Full install log attached

Any clue ?

**Comment by robertklep** [comment]
The version of `npm` that you're using (v1.4.21) is severely outdated. Your Node.js version (v8.11.1) also isn't very recent.

Deprecation warnings are just that: warnings, not errors. So I think the problems you're having have to do with the outdated npm/Node.js and not this module.

**Comment by Sonusss** [comment]
Thx for the fast reaction.
Now I have Node 10.19.0 and npm 6.13.4 but still got issues...
Obviously it's a question of rights against another github repo...

> npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2020-03-24T11_25_05_124Z-debug.log](https://github.com/robertklep/bosch-xmpp/files/4374954/2020-03-24T11_25_05_124Z-debug.log)

> npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
> npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
> npm ERR! code E401
> npm ERR! 401 UNAUTHORIZED - GET https://github.com/dodo/reconnect-core/tarball/merged
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-03-24T11_25_05_124Z-debug.log
>

**Comment by robertklep** [comment]
I have no idea why Github would return a 401, I also can't reproduce the problem (it installs fine for me). Do you use PiHole or some sort of filtering/antivirus proxy?

**Comment by Sonusss** [comment]
Nope and I can get it with: wget https://github.com/dodo/reconnect-core/tarball/merged on the same host...
What is funny is that from now on, having downloaded the repo file manually, the install works perfectly...
Most probably linked to some TLS keys and challenges.
Anyway Thx for you help and nice code, I'm thrilling to test it against my Buderus TC100
